name: Node.js Bot

on:
  push:
    branches:
      - main # o el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # o la versión de Node.js que estás utilizando

    - name: Install dependencies
      run: npm install

    - name: Run bot
      run: node bot.js # Reemplaza con el nombre de tu script
      
